export const WORKSHOPS2026 = [
  {
    title: "Tower Stacking Game",
    type: "workshop",
    instructors: "Emma Qiu and Eli Drewry",
    description: "Students will compete in groups to see who can create the tallest free-standing tower with limited materials (popsicle sticks, tape, rope, etc). This challenge tests their communication, strategy, and discovering the importance of architecture while getting a chance to win prizes.",
    slidesUrl: "https://canva.link/79sw40e0u4vhk4j",
    panelistInfoUrl: "",
  },
  {
    title: "Intro to Game Development",
    type: "workshop",
    instructors: "Joshua Jin and Paul Macapinlac",
    description: "Learn how the snake game works in this fun workshop! Uncover the secrets of Python and learn to customize your snake. Before you know it, you’ll be a pro game dev with a fully customized snake game.",
    slidesUrl: "https://canva.link/y27fiyfbq1pfd3t",
    panelistInfoUrl: "",
  },
  {
    title: "Battle Bots",
    type: "workshop",
    instructors: "Sofia Matos and Benjamin Garcia",
    description: "Drive XRP Robots on a field to take down your opponents in a game of robot soccer! After interacting with code, you will be able to drive and dribble past other robots to score using teamwork and strategy.",
    slidesUrl: "https://canva.link/6edmsozmzcmhkf2",
    panelistInfoUrl: "",
  },
  {
    title: "Squid Games Several-Legged Pentathalon (STEM Edition)",
    type: "workshop",
    instructors: "Matthew Chen and Paul Macapinlac",
    description: "Inspired by the hit Netflix series “Squid Games,” collaborate with up to 3 of your friends to participate in the STEM Games Several-Legged Pentathlon, where you will be tasked to solve STEM puzzles and activities in an interactive race against time.",
    slidesUrl:
      "https://docs.google.com/presentation/d/10K0MQv8v8IqyC8qRrrJJanGZpn2YVPQUX6VFvdg_1ww/edit?slide=id.gf6d3ad9fd1_0_1011#slide=id.gf6d3ad9fd1_0_1011",
    panelistInfoUrl: "",
  },
  {
    title: "AI Photobooth",
    type: "workshop",
    instructors: "Ridhima Seth and Joshua Jin",
    description: "Do you want to learn more about AI image generation? Come to AI Photobooth! This workshop will show you the basics of how an AI image generator works, and then we’ll let you try it for yourself!",
    slidesUrl: "https://canva.link/p62kuwtzwy1ieb6",
    panelistInfoUrl: "",
  },
  {
    title: "COVID-19 Simulator",
    type: "workshop",
    instructors: "Clemente Irarrazaval and Eli Drewry",
    description: "Students will get an introduction into the field of game development by designing a COVID-19 spread simulator. Using Scratch they’ll explore conditionals, loops, and movement while working through obstacles. Students work in teams to build, test, and modify their own simulation-based game, also encouraging teamwork.",
    slidesUrl: "https://canva.link/5noyqe130bqgdqs",
    panelistInfoUrl: "",
  },
  {
    title: "AI Music",
    type: "workshop",
    instructors: "Matthew Chen and Benjamin Garcia",
    description: "The purpose of this workshop is to teach students how to use suno.com, an AI music website that allows users to create any form of music by simply entering into the prompt bar.",
    slidesUrl: "https://canva.link/ja5m1l7cy6k1zsh",
    panelistInfoUrl: "",
  },
  {
    title: "Bridge Building Competition",
    type: "workshop",
    instructors: "Atharv Panditrao and Clemente Irarrazaval",
    description: "Students will design and build a small bridge using limited materials. They will learn basic structural concepts, apply problem-solving skills, and work collaboratively to create a bridge that can hold the greatest load. Students compete in teams and test their designs in a fun final challenge.",
    slidesUrl: "https://canva.link/6ov265jv8fwkeql",
    panelistInfoUrl: "",
  },
  {
    title: "Live Coding Music",
    type: "workshop",
    instructors: "Ana Laura Santana and Atharv Panditrao",
    description: "Sometimes learning code can seem like it’s exclusively professional or something you will never see in your career. But in truth, coding can be useful for all types of passions beyond a corporate life, which is what gives it its beauty. In this workshop, you will learn how to become a DJ using only code!",
    slidesUrl: "https://canva.link/9pwbi4o0ztadleh",
    panelistInfoUrl: "",
  },
  {
    title: "Prompt Engineering",
    type: "workshop",
    instructors: "Alexander Chien and Arjun Asudani",
    description: "Join our prompt engineering workshop to learn how to make the most out of your AI credits. Today’s chat models have vast capabilities, but accessing these skills can be more nuanced than just a straightforward question. We’ll cover prompting methods you can use to ensure you get the results you want. Let’s harness the power of AI!",
    slidesUrl:
      "https://docs.google.com/presentation/d/1IJsZaSjOSEOXJBQJAjdo4N0Zz3iFHkn5otzM8JBI4do/edit?usp=sharing",
    panelistInfoUrl: "",
  },
  {
    title: "How Machines can learn like humans (Neural Networks)",
    type: "workshop",
    instructors: "Ana Laura Santana and Emma Qiu",
    description: "Students will learn the basics of neural networks, and how they are present in our everyday lives. They will also get hands-on experience with neural networks by loading data and training their own model. In the end, students will gain a conceptual understanding and practical skills in AI, which has become increasingly influential in the tech world.",
    slidesUrl: "https://canva.link/t49ze6ojz5edwil",
    panelistInfoUrl: "",
  },
  {
    title: "AI Guess Who",
    type: "workshop",
    instructors: "Ridhima Seth and Amy Lloyd",
    description: "Want to master Guess Who? with logic and strategy? Learn how decision trees and probability help you ask the smartest questions, minimize guesswork, and consistently win. This session makes algorithmic thinking fun and practical—sharpen your problem-solving skills while gaining a competitive edge in both games and real-world decision-making!",
    slidesUrl: "",
    panelistInfoUrl: "",
  },
  {
    title: "Game Theory",
    type: "workshop",
    instructors: "Arjun Asudani and Alexander Chien",
    description: "What would you do if your success depended on someone else’s choice? This interactive workshop introduces game theory through fast-paced games and real-life scenarios. You’ll explore why people compete, when cooperation fails, and how small incentives can completely change outcomes.",
    slidesUrl: "",
    panelistInfoUrl: "",
  },
  {
    title: "Careers in Tech Panel",
    type: "panel",
    instructors: "Meet Modi / Tammy Sujaritchai and Sofia Matos",
    description: "Curious about what a career in tech actually looks like? Join us for a discussion with students and professionals as they share their experiences, career paths, and advice for breaking into the industry. Learn about different roles in tech, what skills matter most, and how to start exploring your own path.",
    slidesUrl: "",
    panelistInfoUrl: "https://docs.google.com/document/d/1Gaj_cB8Y7RgeDnxmjOmZGS6XhREWHHRYwg-b7EyUBiw/edit?usp=sharing",
  },
  {
    title: "CS/Tech in College Panel",
    type: "panel",
    instructors: "Meet Modi / Tammy Sujaritchai and Amy Lloyd",
    description: "What is it really like to study computer science or tech in college? In this panel, students will talk about classes, projects, internships, clubs, and how they found their place in tech. Come ask questions, hear honest advice, and get a better sense of what the college experience can look like.",
    slidesUrl: "https://docs.google.com/presentation/d/1XCDfJbdINGh4_OCPuUYX9roVqXul3N04L3zM6cUqm5M/edit?usp=sharing",
    panelistInfoUrl: "https://docs.google.com/document/d/1Fkc3Ot_d7xpQTU8_oOfYIu_ugJzcenvjnlOOvWkVBBM/edit?usp=sharing",
  },
];