export const Leadership = [
    {
        key: 1,
        name: 'Spoorthy Nalumachu',
        title: 'Executive Director',
        image: require('static/team/leadership/2027/spoorthy-nalumachu.jpg'),
        link: 'https://www.linkedin.com/in/spoorthy-nalumachu',
    }, {
        key: 2,
        name: 'Clara Zhang',
        title: 'Executive Director',
        image: require('static/team/leadership/2027/clara-zhang.jpg'),
        link: 'https://www.linkedin.com/in/clara-zhang-009497197/',
    }, {
        key: 3,
        name: 'Annika Renganathan',
        title: 'External Advisor',
        image: require('static/team/leadership/annika-renganathan.jpg'),
        link: 'https://www.linkedin.com/in/annika-renganathan-b437022b9',
    }, {
        key: 4,
        name: 'Shaina Grover',
        title: 'Content Advisor',
        image: require('static/team/leadership/shaina-grover.jpg'),
        link: 'https://www.linkedin.com/in/shaina-grover',
    }, {
        key: 5,
        name: 'Sandra Pan',
        title: 'Design Advisor',
        image: require('static/team/leadership/sandra-pan.jpg'),
        link: 'https://www.linkedin.com/in/sandra-pan-b994802aa',
    }, {
        key: 6,
        name: 'Eli Drewry',
        title: 'Content Director',
        image: require('static/team/leadership/2027/eli-drewry.jpg'),
        link: '',
    }, {
        key: 7,
        name: 'Matthew Chen',
        title: 'Content Director',
        image: require('static/team/leadership/2027/matthew-chen.jpg'),
        link: '',
    }, {
        key: 8,
        name: 'Isabelle Chang',
        title: 'Design Director & UI/UX Design Lead',
        image: require('static/team/design/isabelle-chang.png'),
        link: '',
    }, {
        key: 9,
        name: 'Sarah Zhao',
        title: 'Design Director',
        image: require('static/team/leadership/2027/sarah-zhao.jpg'),
        link: '',
    }, {
        key: 10,
        name: 'Eric Chen',
        title: 'Operations Director',
        image: require('static/team/leadership/2027/eric-chen.jpg'),
        link: '',
    }, {
        key: 11,
        name: 'Christina Uong',
        title: 'Operations Director',
        image: require('static/team/leadership/2027/christina-uong.jpg'),
        link: '',
    }, {
        key: 12,
        name: 'Sadie Scott',
        title: 'External Director',
        image: require('static/team/leadership/2027/sadie-scott.jpg'),
        link: '',
    }, {
        key: 13,
        name: 'Jubilee Yul',
        title: 'External Director',
        image: require('static/team/leadership/2027/jubilee-yul.jpg'),
        link: '',
    }, {
        key: 14,
        name: 'Benjamin Garcia',
        title: 'Web Dev Lead',
        image: require('static/team/content/benjamin-garcia.jpg'),
        link: '',
    },
];
