import images from "./optimizedImages";

export const Leadership = [
  {
    key: 1,
    name: "Spoorthy Nalumachu",
    title: "Executive Director",
    image: images["team/leadership/2027/spoorthy-nalumachu.jpg"].src,
    link: "https://www.linkedin.com/in/spoorthy-nalumachu",
  },
  {
    key: 2,
    name: "Clara Zhang",
    title: "Executive Director",
    image: images["team/leadership/2027/clara-zhang.jpg"].src,
    link: "https://www.linkedin.com/in/clara-zhang-009497197/",
  },
  {
    key: 3,
    name: "Annika Renganathan",
    title: "External Advisor",
    image: images["team/leadership/annika-renganathan.jpg"].src,
    link: "https://www.linkedin.com/in/annika-renganathan-b437022b9",
  },
  {
    key: 4,
    name: "Shaina Grover",
    title: "Content Advisor",
    image: images["team/leadership/shaina-grover.jpg"].src,
    link: "https://www.linkedin.com/in/shaina-grover",
  },
  {
    key: 5,
    name: "Sandra Pan",
    title: "Design Advisor",
    image: images["team/leadership/sandra-pan.jpg"].src,
    link: "https://www.linkedin.com/in/sandra-pan-b994802aa",
  },
  {
    key: 6,
    name: "Eli Drewry",
    title: "Content Director",
    image: images["team/leadership/2027/eli-drewry.jpg"].src,
    link: "",
  },
  {
    key: 7,
    name: "Matthew Chen",
    title: "Content Director",
    image: images["team/leadership/2027/matthew-chen.jpg"].src,
    link: "",
  },
  {
    key: 8,
    name: "Isabelle Chang",
    title: "Design Director & UI/UX Design Lead",
    image: images["team/design/isabelle-chang.png"].src,
    link: "",
  },
  {
    key: 9,
    name: "Sarah Zhao",
    title: "Design Director",
    image: images["team/leadership/2027/sarah-zhao.jpg"].src,
    link: "",
  },
  {
    key: 10,
    name: "Eric Chen",
    title: "Operations Director",
    image: images["team/leadership/2027/eric-chen.jpg"].src,
    link: "",
  },
  {
    key: 11,
    name: "Christina Uong",
    title: "Operations Director",
    image: images["team/leadership/2027/christina-uong.jpg"].src,
    link: "",
  },
  {
    key: 12,
    name: "Sadie Scott",
    title: "External Director",
    image: images["team/leadership/2027/sadie-scott.jpg"].src,
    link: "",
  },
  {
    key: 13,
    name: "Jubilee Yul",
    title: "External Director",
    image: images["team/leadership/2027/jubilee-yul.jpg"].src,
    link: "",
  },
  {
    key: 14,
    name: "Benjamin Garcia",
    title: "Web Dev Lead",
    image: images["team/content/benjamin-garcia.jpg"].src,
    link: "",
  },
];
